---
- name: To install Httpd on web servers
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum: 
      name: httpd
      state: installed


  - name: start apache
    service:
      name: httpd
      state: started
