---
- name: To install Httpd on web servers
  hosts: webserver
  become: true
  tasks:
  - name: install packages
    yum: 
      name: httpd
      state: installed
    notify: start apache  

  - name: start apache
    service:
      name: httpd
      state: started
